name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ["v0.12.0", "stable", "nightly"]
    steps:
      - uses: actions/checkout@v6
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}
      - uses: jdx/mise-action@v2
      - run: mise exec -- nvim -u NONE --headless -l test/typecheck.lua
      - run: nvim -u NONE -l test/run.lua
